package com.myspace.provider_selection;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Server implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer cpu;
	private java.lang.Integer memory;
	private java.lang.Integer disk;
	private java.lang.Integer monthlyPrice;
	private java.lang.String providedby;
	private java.lang.Boolean selected;

	public Server() {
	}

	public java.lang.Integer getCpu() {
		return this.cpu;
	}

	public void setCpu(java.lang.Integer cpu) {
		this.cpu = cpu;
	}

	public java.lang.Integer getMemory() {
		return this.memory;
	}

	public void setMemory(java.lang.Integer memory) {
		this.memory = memory;
	}

	public java.lang.Integer getDisk() {
		return this.disk;
	}

	public void setDisk(java.lang.Integer disk) {
		this.disk = disk;
	}

	public java.lang.Integer getMonthlyPrice() {
		return this.monthlyPrice;
	}

	public void setMonthlyPrice(java.lang.Integer monthlyPrice) {
		this.monthlyPrice = monthlyPrice;
	}

	public java.lang.String getProvidedby() {
		return this.providedby;
	}

	public void setProvidedby(java.lang.String providedby) {
		this.providedby = providedby;
	}

	public java.lang.Boolean getSelected() {
		return this.selected;
	}

	public void setSelected(java.lang.Boolean selected) {
		this.selected = selected;
	}

	public Server(java.lang.Integer cpu, java.lang.Integer memory,
			java.lang.Integer disk, java.lang.Integer monthlyPrice,
			java.lang.String providedby, java.lang.Boolean selected) {
		this.cpu = cpu;
		this.memory = memory;
		this.disk = disk;
		this.monthlyPrice = monthlyPrice;
		this.providedby = providedby;
		this.selected = selected;
	}

}
